name: Build and Deploy

on:
  push:
    branches:
      - main
env:
  NEXT_PUBLIC_CORS_URL: ${{secrets.NEXT_PUBLIC_CORS_URL}}
  NEXT_PUBLIC_GA_MEASUREMENT_ID: ${{secrets.NEXT_PUBLIC_GA_MEASUREMENT_ID}}
  NEXT_PUBLIC_APP_URL: ${{secrets.NEXT_PUBLIC_APP_URL}}
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install Dependencies
        run: yarn install

      - name: Build Website
        run: yarn build

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: "unnecessary"

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Install rsync
        uses: GuillaumeFalourd/setup-rsync@v1.1

      - name: Push .next with rsync
        run: rsync -avz --delete ./.next ${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.TARGET_DIRECTORY }}

      - name: Restart Sever
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd ~/truyendex-frontend
            git pull origin main
            git status
            yarn install
            pm2 restart truyendex-frontend
